name: Build Docker Image - CI

on:
  release:
    types:
      - published
  push:
    branches:
      - main
      - master
      - 'release-\d.\d\d'

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: |
          image_tag=latest
          if [ ${{ github.ref }} == 'refs/heads/release-\d.\d\d' ]; then
            branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
            version_digits=$(echo ${branch} | tr -d -c 0-9)
            image_tag=v$(echo ${version_digits} | cut -b 1).$(echo ${version_digits:1})
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
        id: set_image_tag

      - name: Set up QEMU
        run: |
          ls -l
          cat main/main.go
          echo "Variable is ${{ steps.set_image_tag.outputs.IMAGE_TAG }}"
