name: Build Docker Image - CI

on:
  release:
    types:
      - published
  push:
    branches:
      - release-1

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set up QEMU
        run: |
          ls -l
          cat main/main.go
          echo "Image pushed to ${{ steps.extract_branch.outputs.branch }}"
        # uses: docker/setup-qemu-action@v3

